language: java
sudo: true
install: true

os:
  - linux

dist: xenial

jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk14
  - oraclejdk11
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - chmod +x ./gradlew
  - ./gradlew build
  - ./gradlew check --rerun-tasks

after_success:
  - ./gradlew jacocoTestReport coveralls
